#!/usr/bin/env python3
"""Assemble design-system/index.html from kit/tokens.css + components/*.html.

Stdlib only. Re-run after editing any component fragment or tokens.css:

    python3 build_gallery.py

The gallery is a single self-contained file (fonts load from Google Fonts
with a robust local fallback stack; everything else is inline).
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
KIT = HERE.parent / "kit"

# Gallery order — foundations section is generated by the shell itself.
FRAGMENTS = [
    "buttons.html",
    "cards.html",
    "hero.html",
    "navigation.html",
    "data.html",
    "interactive.html",
    "photo.html",
]

CHROME_CSS = """
/* ---- gallery chrome (not part of the kit) ---- */
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: var(--font-sans);
  background: var(--color-bg-base);
  color: var(--color-text-body);
  font-size: var(--text-body-s);
  line-height: var(--leading-body);
}
.g-header {
  padding: var(--space-800) var(--gutter) var(--space-600);
  max-width: var(--container-max);
  margin: 0 auto;
}
.g-header h1 {
  font-size: var(--text-h2);
  font-weight: var(--weight-extrabold);
  letter-spacing: var(--tracking-h2);
  line-height: var(--leading-heading);
  color: var(--color-text-heading);
  margin: 0 0 var(--space-200);
}
.g-header p {
  margin: 0;
  max-width: var(--container-text);
  color: var(--color-text-secondary);
}
.g-topbar {
  display: flex; flex-wrap: wrap; gap: var(--space-300);
  align-items: center; justify-content: space-between;
  max-width: var(--container-max); margin: 0 auto;
  padding: var(--space-300) var(--gutter);
  border-bottom: 1px solid var(--color-divider);
  position: sticky; top: 0; z-index: 50;
  background: var(--color-bg-base);
}
.g-toc { display: flex; flex-wrap: wrap; gap: var(--space-100) var(--space-400); }
.g-toc a {
  color: var(--color-text-secondary); text-decoration: none;
  font-weight: var(--weight-semibold); font-size: var(--text-detail);
}
@media (hover: hover) and (pointer: fine) {
  .g-toc a:hover { color: var(--color-text-heading); }
}
.g-toc a:focus-visible { box-shadow: var(--focus-ring); outline: none; border-radius: var(--radius-s); }
.g-theme { display: inline-flex; border: 1px solid var(--color-border); border-radius: var(--radius-pill); padding: var(--space-50); gap: var(--space-50); }
.g-theme button {
  font: inherit; font-size: var(--text-caption); font-weight: var(--weight-semibold);
  border: 0; background: transparent; color: var(--color-text-secondary);
  padding: var(--space-75) var(--space-300); border-radius: var(--radius-pill); cursor: pointer;
}
.g-theme button[aria-pressed="true"] { background: var(--color-text-heading); color: var(--color-bg-base); }
.g-theme button:focus-visible { box-shadow: var(--focus-ring); outline: none; }
main { max-width: var(--container-max); margin: 0 auto; padding: 0 var(--gutter) var(--space-1000); }
.ds-demo { padding: var(--space-800) 0; border-top: 1px solid var(--color-divider); }
.ds-demo:first-of-type { border-top: 0; }
.g-sec-title {
  font-size: var(--text-h3); font-weight: var(--weight-extrabold);
  letter-spacing: var(--tracking-h2); color: var(--color-text-heading);
  margin: 0 0 var(--space-500);
}
.ds-row { display: flex; flex-wrap: wrap; gap: var(--space-400); align-items: center; margin: 0 0 var(--space-500); }
.ds-label {
  display: block; width: 100%;
  font-size: var(--text-caption); font-weight: var(--weight-semibold);
  letter-spacing: var(--tracking-detail); text-transform: uppercase;
  color: var(--color-text-tertiary); margin: var(--space-500) 0 var(--space-200);
}
.g-foot {
  border-top: 1px solid var(--color-divider);
  max-width: var(--container-max); margin: 0 auto;
  padding: var(--space-500) var(--gutter);
  font-size: var(--text-caption); color: var(--color-text-tertiary);
}
/* foundations */
.g-swatches { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: var(--space-300); margin-bottom: var(--space-500); }
.g-swatch { border: 1px solid var(--color-divider); border-radius: var(--radius-m); overflow: hidden; }
.g-swatch-chip { height: var(--space-800); }
.g-swatch-meta { padding: var(--space-100) var(--space-200); font-size: var(--text-caption); }
.g-swatch-meta code { font-family: var(--font-mono); color: var(--color-text-tertiary); font-size: var(--text-caption); display: block; }
.g-type-row { display: flex; align-items: baseline; gap: var(--space-400); margin-bottom: var(--space-300); }
.g-type-row code { font-family: var(--font-mono); font-size: var(--text-caption); color: var(--color-text-tertiary); min-width: 10rem; }
.g-radius-row { display: flex; gap: var(--space-400); flex-wrap: wrap; }
.g-radius-box {
  width: var(--space-1000); height: var(--space-900);
  background: var(--color-bg-layer-1); border: 1px solid var(--color-border);
  display: flex; align-items: center; justify-content: center;
  font-size: var(--text-caption); color: var(--color-text-tertiary); font-family: var(--font-mono);
}
"""

FOUNDATIONS_HTML = """
<section class="ds-demo" id="demo-foundations" data-title="Foundations">
  <span class="ds-label">Color — semantic roles (theme-aware)</span>
  <div class="g-swatches" data-swatches="--brand-red --brand-red-hover --color-bg-base --color-bg-layer-1 --color-bg-elevated --color-bg-dark-section --color-text-heading --color-text-body --color-text-secondary --color-text-tertiary --color-border --color-link --color-positive --color-negative --color-notice --color-informative"></div>
  <span class="ds-label">Type scale (Source Sans 3 — Adobe Clean substitute)</span>
  <div>
    <div class="g-type-row"><code>--text-hero / 900</code><span style="font-size:var(--text-hero);font-weight:var(--weight-black);letter-spacing:var(--tracking-hero);line-height:var(--leading-hero);color:var(--color-text-heading)">Aa</span></div>
    <div class="g-type-row"><code>--text-h2 / 800</code><span style="font-size:var(--text-h2);font-weight:var(--weight-extrabold);letter-spacing:var(--tracking-h2);color:var(--color-text-heading)">Heading two</span></div>
    <div class="g-type-row"><code>--text-h3 / 800</code><span style="font-size:var(--text-h3);font-weight:var(--weight-extrabold);color:var(--color-text-heading)">Heading three</span></div>
    <div class="g-type-row"><code>--text-lede / 400</code><span style="font-size:var(--text-lede);color:var(--color-text-secondary)">Lede paragraph under a hero.</span></div>
    <div class="g-type-row"><code>--text-body / 400</code><span style="font-size:var(--text-body)">Marketing body copy at eighteen pixels.</span></div>
    <div class="g-type-row"><code>--text-detail / 600</code><span style="font-size:var(--text-detail);font-weight:var(--weight-semibold);letter-spacing:var(--tracking-detail);text-transform:uppercase;color:var(--color-text-tertiary)">Detail / eyebrow</span></div>
  </div>
  <span class="ds-label">Corner radius</span>
  <div class="g-radius-row">
    <div class="g-radius-box" style="border-radius:var(--radius-s)">s</div>
    <div class="g-radius-box" style="border-radius:var(--radius-m)">m</div>
    <div class="g-radius-box" style="border-radius:var(--radius-l)">l</div>
    <div class="g-radius-box" style="border-radius:var(--radius-xl)">xl</div>
    <div class="g-radius-box" style="border-radius:var(--radius-xxl)">xxl</div>
    <div class="g-radius-box" style="border-radius:var(--radius-pill)">pill</div>
  </div>
  <span class="ds-label">Elevation</span>
  <div class="g-radius-row">
    <div class="g-radius-box" style="border:0;box-shadow:var(--shadow-card);background:var(--color-bg-elevated);border-radius:var(--radius-m)">card</div>
    <div class="g-radius-box" style="border:0;box-shadow:var(--shadow-elevated);background:var(--color-bg-elevated);border-radius:var(--radius-m)">elevated</div>
    <div class="g-radius-box" style="border:0;box-shadow:var(--shadow-dragged);background:var(--color-bg-elevated);border-radius:var(--radius-m)">dragged</div>
  </div>
</section>
"""

SHELL_JS = """
(function () {
  // Theme control — same attribute + storage key the kit's theme toggle uses.
  var KEY = 'adb-theme';
  var root = document.documentElement;
  function apply(mode) {
    if (mode === 'light' || mode === 'dark') root.setAttribute('data-theme', mode);
    else root.removeAttribute('data-theme');
    document.querySelectorAll('.g-theme button').forEach(function (b) {
      b.setAttribute('aria-pressed', String(b.dataset.mode === (mode || 'auto')));
    });
  }
  document.querySelectorAll('.g-theme button').forEach(function (b) {
    b.addEventListener('click', function () {
      var mode = b.dataset.mode;
      if (mode === 'auto') localStorage.removeItem(KEY);
      else localStorage.setItem(KEY, mode);
      apply(mode === 'auto' ? null : mode);
    });
  });
  apply(localStorage.getItem(KEY));

  // Inject section titles from data-title.
  document.querySelectorAll('.ds-demo[data-title]').forEach(function (sec) {
    if (sec.querySelector('.g-sec-title')) return;
    var h = document.createElement('h2');
    h.className = 'g-sec-title';
    h.textContent = sec.getAttribute('data-title');
    sec.prepend(h);
  });

  // Foundations swatches — rendered from live computed token values so the
  // grid always matches tokens.css and the active theme.
  function renderSwatches() {
    document.querySelectorAll('[data-swatches]').forEach(function (grid) {
      grid.innerHTML = '';
      var cs = getComputedStyle(root);
      grid.getAttribute('data-swatches').split(/\\s+/).forEach(function (name) {
        var val = cs.getPropertyValue(name).trim();
        var card = document.createElement('div');
        card.className = 'g-swatch';
        var chip = document.createElement('div');
        chip.className = 'g-swatch-chip';
        chip.style.background = 'var(' + name + ')';
        var meta = document.createElement('div');
        meta.className = 'g-swatch-meta';
        var label = document.createElement('strong');
        label.textContent = name.replace(/^--(color-|brand-)?/, '');
        var code = document.createElement('code');
        code.textContent = val;
        meta.append(label, code);
        card.append(chip, meta);
        grid.append(card);
      });
    });
  }
  function syncButtons() {
    var stored = null;
    try { stored = localStorage.getItem(KEY); } catch (err) { /* storage unavailable */ }
    var mode = (stored === 'light' || stored === 'dark') ? stored : 'auto';
    document.querySelectorAll('.g-theme button').forEach(function (b) {
      b.setAttribute('aria-pressed', String(b.dataset.mode === mode));
    });
  }
  renderSwatches();
  new MutationObserver(function () { renderSwatches(); syncButtons(); })
    .observe(root, { attributes: true, attributeFilter: ['data-theme'] });
  if (window.matchMedia) {
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', renderSwatches);
  }
})();
"""


def main():
    tokens = (KIT / "tokens.css").read_text()

    toc, body = [], []
    toc.append('<a href="#demo-foundations">Foundations</a>')
    body.append(FOUNDATIONS_HTML)
    for name in FRAGMENTS:
        frag = (HERE / "components" / name).read_text().strip()
        m = re.search(r'id="(demo-[\w-]+)"[^>]*data-title="([^"]+)"', frag)
        if not m:
            raise SystemExit(f"{name}: fragment root must carry id + data-title")
        toc.append(f'<a href="#{m.group(1)}">{m.group(2)}</a>')
        body.append(frag)

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Adobe-Style Design System</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700;800;900&family=Source+Code+Pro:wght@400;600&display=swap" rel="stylesheet">
<!-- kit/tokens.css inlined by build_gallery.py — edit the kit file, not this copy -->
<style>
{tokens}
</style>
<style>
{CHROME_CSS}
</style>
</head>
<body>
<div class="g-topbar">
  <nav class="g-toc">{''.join(toc)}</nav>
  <div class="g-theme" role="group" aria-label="Theme">
    <button type="button" data-mode="auto" aria-pressed="true">Auto</button>
    <button type="button" data-mode="light" aria-pressed="false">Light</button>
    <button type="button" data-mode="dark" aria-pressed="false">Dark</button>
  </div>
</div>
<header class="g-header">
  <h1>Adobe-Style Design System</h1>
  <p>Spectrum-2-derived tokens, components, and motion for proposal sites.
     Styled after Adobe's visual language; not an Adobe product. Fonts:
     Source Sans 3 &amp; Source Code Pro (Adobe Clean substitutes).</p>
</header>
<main>
{''.join(body)}
</main>
<footer class="g-foot">
  Tokens verified against @adobe/spectrum-tokens 14.14.0 · motion per
  design-system/motion.md · craft rules per design-system/craft-rules.md ·
  rebuild with <code>python3 build_gallery.py</code>
</footer>
<script>
{SHELL_JS}
</script>
</body>
</html>
"""
    out = HERE / "index.html"
    out.write_text(html)
    print(f"wrote {out} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
